# nixpacks.toml

[project]
name = "multi-modal-medical-imaging"

[phases.setup]
# setup phase installs dependencies
cmds = [
    "echo 'Setting up environment...'",
    "cd frontend && npm install",
    "pip install -r backend/requirements.txt"
]

[phases.build]
# build phase compiles React and collects Django static files
cmds = [
    "echo 'Building frontend...'",
    "cd frontend && npm run build",
    "echo 'Copying frontend build to Django static folder...'",
    "mkdir -p backend/static",
    "cp -r frontend/dist/* backend/static/",
    "echo 'Running Django migrations...'",
    "cd backend && python manage.py migrate"
]

[start]
cmd = "cd backend && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
