[build]
provider = "python"

[build.python]
version = "3.10"

[build.node]
version = "18"

[[phases]]
name = "setup"
cmds = ["cd frontend && npm install"]

[[phases]]
name = "build"
cmds = [
    "cd frontend && npm run build",
    "pip install -r backend/requirements.txt"
]

[start]
cmd = "cd backend && python manage.py migrate && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
