[project]
name = "multi-modal-medical-imaging"

[phases.setup]
cmds = [
    # explicitly install Node and Python together
    "nix-env -iA nixpkgs.nodejs-18_x",   # install Node 18
    "cd frontend && npm install",
    "pip install -r backend/requirements.txt"
]

[phases.build]
cmds = [
    "cd frontend && npm run build",
    "mkdir -p backend/static",
    "cp -r frontend/dist/* backend/static/",
    "cd backend && python manage.py migrate"
]

[start]
cmd = "cd backend && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
