[build]
provider = "multi"

[build.python]
version = "3.10"

[build.node]
version = "18"

[phases.setup]
cmds = [
    "cd frontend && npm install",
    "pip install -r backend/requirements.txt"
]

[phases.build]
cmds = [
    "cd frontend && npm run build",
    "mkdir -p backend/static",
    "cp -r frontend/dist/* backend/static/",
    "cd backend && python manage.py migrate"
]

[start]
cmd = "cd backend && gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
